id: opecha:P000420
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG13603
  title: རྫོགས་པ་ཆེན་པོ་ཡེ་ཤེས་བླ་མའི་སྤྱི་དོན་སྙིང་ཐིག་མ་བུའི་ལྡེ་མིག་ཀུན་བཟང་ཐུགས་ཀྱི་ཊི་ཀ
  volume:
    90a013a3e4074007a2123f1d4df4b580:
      image_group_id: I1KG13627
      title: Volume 1 of rdzogs pa chen po ye shes bla ma'i spyi don snying thig ma
        bu'i lde mig kun bzang thugs kyi Ti ka
      volume_number: 1
      total_pages: 610
  author: ''
ebook_metadata:
  title: རྫོགས་པ་ཆེན་པོ་ཡེ་ཤེས་བླ་མའི་སྤྱི་དོན་སྙིང་ཐིག་མ་བུའི་ལྡེ་མིག་ཀུན་བཟང་ཐུགས་ཀྱི་ཊི་ཀ
  author: ''
  sku: P000420
  cover: cover.jpg
  layers:
  - pagination
