id: P000420
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-16 15:39:02.515827
source_metadata:
  id: bdr:W1KG13603
  title: རྫོགས་པ་ཆེན་པོ་ཡེ་ཤེས་བླ་མའི་སྤྱི་དོན་སྙིང་ཐིག་མ་བུའི་ལྡེ་མིག་ཀུན་བཟང་ཐུགས་ཀྱི་ཊི་ཀ
  author: ''
  volumes:
    90a013a3e4074007a2123f1d4df4b580:
      image_group_id: I1KG13627
      title: Volume 1 of rdzogs pa chen po ye shes bla ma'i spyi don snying thig ma
        bu'i lde mig kun bzang thugs kyi Ti ka
      volume_number: 1
      total_pages: 610
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
