id: opecha:P000420
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG13603
  title: རྫོགས་པ་ཆེན་པོ་ཡེ་ཤེས་བླ་མའི་སྤྱི་དོན་སྙིང་ཐིག་མ་བུའི་ལྡེ་མིག་ཀུན་བཟང་ཐུགས་ཀྱི་ཊི་ཀ
  volume: ''
  author: ''
